### ISSUE TITLE
command suggestion

### ISSUE THREAD

**Issue by ZenonLiao** [j3soon/LLM-Tutorial#1]
https://github.com/j3soon/LLM-Tutorial/blob/eb7dd6b7b612810a5fbe258340e6b6cfc01bb10b/README_TWCC.md?plain=1#L49C1-L56C54

after cloning this repo, one should first check if there is critical data in the `/workspace` then doing `sudo rm -rf` for safety.

**Comment by j3soon** [comment]
I agree with you, and have just pushed a fix, thanks!
